#ifndef __DEFINATIONS_H__
#define __DEFINATIONS_H__

#define TRANSITION_TIME 0.01

#define PLAYER_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002

#define PLAYER_JUMP_SPEED 0.0250
#define PLAYER_FALL_SPEED 0.050
//#define PLAYER_FALL_SPEED 0.0008
#define PLAYER_JUMP_DURATION 0.50


#define PLATFORM_SPAWN_TIME 0.002
#define PLATFORM_GAP 10
#define UPPER_SCREEN_PLATFORM_THRESHOLD 0.80
#define LOWER_SCREEN_PLATFORM_THRESHOLD 0.20
#define PLATFORM_MOVE_SPEED 0.01

#endif // __DEFINITIONS_H__
